import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Calendar, User } from "lucide-react";
import { useEffect, useState } from "react";
import { apiClient } from "@/lib/apiClient";

export const Route = createFileRoute("/blog")({
  head: () => ({
    meta: [
      { title: "Stories & Inspiration — Giftcy Blog" },
      { name: "description", content: "Explore the Giftcy blog. Guides on sustainable luxury gifting, packaging ideas, and glimpses into the heritage of our weavers." },
    ],
  }),
  component: BlogPage,
});

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  image: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "sustainable-gifting-guide",
    title: "The Ultimate Guide to Sustainable Luxury Gifting",
    excerpt: "Discover how to balance opulence with eco-consciousness. A guide to making your gift wrap as premium and reusable as the gift itself.",
    category: "Guides",
    date: "June 05, 2026",
    readTime: "5 min read",
    author: "Aditi Sharma",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800",
    content: `
Gifting is an ancient art in India, representing honor, connection, and celebration. However, as festivals and wedding seasons roll by, the volume of waste generated by single-use wrapping paper and plastic laminates spikes dramatically.

At Giftcy, we believe luxury and sustainability are not mutually exclusive. In fact, true luxury lies in longevity, craft, and respect for our environment. Here’s how you can make your celebrations sustainable without compromising on aesthetics.

### 1. The Wrapper is Part of the Gift
Traditional wrapping paper is used for less than a minute before being discarded. Reusable fabric gift bags, however, become part of the present. A recipient can reuse a silk potli bag or a premium cotton envelope for years, passing on the gesture of conscious giving.

### 2. Choose Natural and Handloomed Fabrics
Opt for gift wraps made from organic cotton, linen, jute, or hand-loomed silk. These materials are biodegradable, support local karigars (artisans), and carry a unique tactile charm that mass-produced paper simply cannot replicate.

### 3. Personalization Over Decoration
Instead of plastic ribbons, bows, and synthetic stickers, personalize your gift wrapping. A gold-foil monogram of the recipient's initials or a handwritten note on recycled cardstock feels warmer and adds custom luxury.
    `
  },
  {
    slug: "heritage-weaves-indian-karigars",
    title: "Preserving Heritage: At Home with India's Master Karigars",
    excerpt: "Step behind the scenes into the artisanal workshops of Gujarat and Rajasthan, where every thread tells a story of heritage and craft.",
    category: "Heritage",
    date: "May 28, 2026",
    readTime: "7 min read",
    author: "Rohan Verma",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    content: `
Behind every Giftcy bag is the steady hand of a master artisan. In the vibrant clusters of Jaipur and Ahmedabad, our karigars preserve techniques passed down through generations.

From delicate Gota-Patti embroidery to the gold-zari weaving of Banarasi brocades, these fabrics carry India’s rich textile heritage.

### A Legacy of Ateliers
We work with women-led weaving circles and multi-generational workshops. By paying fair wages and providing continuous employment, we ensure these historic crafts remain viable in a fast-fashion world.

### The Beauty of Imperfections
Unlike machine-made synthetic wraps, hand-loomed fabrics possess small variations in weave and texture. These are not flaws; they are the thumbprints of the artisans, making each Giftcy bag truly one-of-a-kind.
    `
  },
  {
    slug: "packaging-ideas-wedding-favors",
    title: "5 Elegant Packaging Ideas for Wedding Favors",
    excerpt: "Make a memorable first impression. Expert wedding decorators share their favorite ways to present favors using fabric pouches and custom details.",
    category: "Weddings",
    date: "May 15, 2026",
    readTime: "4 min read",
    author: "Pooja Mehta",
    image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800",
    content: `
Your wedding day is a tapestry of memorable details. When it comes to bidai or welcome hampers, the packaging sets the expectation. Here are 5 ways to present your favors:

1. **The Royal Velvet Drawstring**: Perfect for jewelry, silver coins, or gourmet sweets. Emerald and wine velvet drawstrings with gold tassels look incredibly opulent.
2. **Monogrammed Linen Envelopes**: Ideal for sangeet cards, dry fruit assortments, or customized invitations.
3. **The Banarasi Zari Potli**: Traditional yet timeless, these bags match classic Indian bridal wear and add festive heritage to any dining setup.
4. **Color-Coordinated Theme Collections**: Match your bag colors with your floral decor — e.g. pastel blush rose wraps for daytime garden sangeets.
5. **A Hand-tied Tassel Accent**: Give simple organic cotton pouches a premium lift with hand-sewn gota borders and silk tassels.
    `
  }
];

function BlogPage() {
  const [blogs, setBlogs] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const res = await apiClient.get("/blogs");
        if (res?.success && Array.isArray(res.data) && res.data.length > 0) {
          const mapped = res.data.map((b: any) => ({
            slug: b.slug,
            title: b.title,
            excerpt: b.excerpt || b.content.substring(0, 150) + "...",
            content: b.content,
            image: b.featuredImage,
            category: b.metaTitle || "Editorial",
            date: new Date(b.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
            readTime: "5 min read",
            author: b.author || "Editor"
          }));
          setBlogs(mapped);
        } else {
          setBlogs(BLOG_POSTS);
        }
      } catch (err) {
        console.error("Failed to load blogs from API", err);
        setBlogs(BLOG_POSTS);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const featured = blogs[0] || BLOG_POSTS[0];
  const gridPosts = blogs.slice(1);

  return (
    <>
      <section className="mx-auto max-w-5xl px-5 lg:px-10 py-16 lg:py-20 text-center">
        <p className="text-[11px] tracking-[0.25em] uppercase text-gold">The Giftcy Editorial</p>
        <h1 className="serif text-5xl lg:text-7xl mt-4 leading-[1.05]">Stories & Inspiration.</h1>
        <p className="mt-5 text-muted-foreground max-w-xl mx-auto">
          Insights into conscious luxury gifting, celebrations, packaging design, and the rich heritage of handcrafted Indian textiles.
        </p>
      </section>

      {/* Featured Editorial Post */}
      <section className="mx-auto max-w-7xl px-5 lg:px-10 pb-12">
        <Link
          to="/blog/$slug"
          params={{ slug: featured.slug }}
          className="group grid md:grid-cols-[1.2fr_1fr] gap-8 md:gap-12 rounded-[2.5rem] overflow-hidden border border-border bg-cream/20 hover:bg-cream/35 transition duration-300"
        >
          <div className="aspect-[16/10] md:aspect-auto md:min-h-[450px] overflow-hidden">
            <img
              src={featured.image}
              alt={featured.title}
              className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]"
            />
          </div>
          <div className="p-8 md:p-12 flex flex-col justify-center">
            <div className="flex items-center gap-3 text-xs text-muted-foreground mb-4">
              <span className="px-3 py-1 rounded-full bg-gold/10 text-gold font-semibold uppercase tracking-wider text-[10px]">
                {featured.category}
              </span>
              <span className="flex items-center gap-1">
                <Calendar className="h-3.5 w-3.5" /> {featured.date}
              </span>
            </div>
            <h2 className="serif text-3xl lg:text-4xl font-semibold mb-4 leading-tight group-hover:text-gold transition-colors">
              {featured.title}
            </h2>
            <p className="text-muted-foreground text-sm lg:text-base leading-relaxed mb-6">
              {featured.excerpt}
            </p>
            <div className="flex items-center gap-2 text-sm font-semibold text-foreground group-hover:translate-x-1.5 transition-transform duration-200">
              Read Article <ArrowRight className="h-4 w-4 text-gold" />
            </div>
          </div>
        </Link>
      </section>

      {/* Editorial Posts Grid */}
      <section className="mx-auto max-w-7xl px-5 lg:px-10 pb-28">
        <div className="grid md:grid-cols-2 gap-8">
          {gridPosts.map((post) => (
            <Link
              key={post.slug}
              to="/blog/$slug"
              params={{ slug: post.slug }}
              className="group flex flex-col rounded-[2rem] overflow-hidden border border-border bg-background hover:shadow-soft transition duration-300"
            >
              <div className="aspect-[16/10] overflow-hidden">
                <img
                  src={post.image}
                  alt={post.title}
                  className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]"
                />
              </div>
              <div className="p-8 flex-1 flex flex-col justify-between">
                <div>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground mb-3">
                    <span className="px-2.5 py-0.5 rounded-full border border-border text-[9px] uppercase tracking-wider font-semibold">
                      {post.category}
                    </span>
                    <span className="flex items-center gap-1">
                      <Calendar className="h-3.5 w-3.5" /> {post.date}
                    </span>
                  </div>
                  <h3 className="serif text-2xl font-semibold mb-3 group-hover:text-gold transition-colors">
                    {post.title}
                  </h3>
                  <p className="text-muted-foreground text-sm leading-relaxed mb-5">
                    {post.excerpt}
                  </p>
                </div>
                <div className="flex items-center gap-1 text-xs font-semibold text-foreground">
                  Read Article <ArrowRight className="h-3.5 w-3.5 text-gold" />
                </div>
              </div>
            </Link>
          ))}
        </div>
      </section>
    </>
  );
}
